import "./globals.css";
import Script from "next/script";
import { AuthProvider } from "@/components/AuthProvider";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import JsonLd from "@/components/JsonLd";
import { Analytics } from "@vercel/analytics/react";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import ChatWidget from "@/components/ChatWidget";
import { organizationLd, websiteLd, SITE_URL } from "@/lib/seo";

const ADSENSE_CLIENT = process.env.NEXT_PUBLIC_ADSENSE_CLIENT;

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "NaijaArtisans — Find trusted artisans & service pros in Nigeria",
    template: "%s | NaijaArtisans",
  },
  description:
    "Hire plumbers, electricians, tailors, caterers and more across Nigeria. Post a job for free and get quotes from skilled artisans near you.",
  keywords: [
    "Nigeria artisans", "find artisan Nigeria", "plumber Lagos", "electrician Abuja",
    "tailor Nigeria", "hire artisan", "service marketplace Nigeria", "handyman Nigeria",
    "post a job Nigeria", "skilled workers Nigeria",
  ],
  applicationName: "NaijaArtisans",
  manifest: "/manifest.webmanifest",
  appleWebApp: { capable: true, statusBarStyle: "default", title: "NaijaArtisans" },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/icon.svg",
    apple: "/icons/apple-touch-icon.png",
  },
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_NG",
    url: SITE_URL,
    siteName: "NaijaArtisans",
    title: "NaijaArtisans — Find trusted artisans in Nigeria",
    description:
      "Plumbers, electricians, tailors, caterers and more. Post a job for free and get quotes from skilled hands near you.",
    // Share image is generated by app/opengraph-image.js (branded banner).
  },
  twitter: {
    card: "summary_large_image",
    title: "NaijaArtisans — Find trusted artisans in Nigeria",
    description: "Hire skilled artisans across Nigeria. Post a job for free and get quotes.",
    // Share image is generated by app/twitter-image.js.
  },
  robots: { index: true, follow: true },
  // Google Search Console verification. Set GOOGLE_SITE_VERIFICATION in Vercel to
  // the code from Search Console's "HTML tag" method — the meta tag then appears
  // automatically. (You also already have an HTML-file verification in /public.)
  verification: process.env.GOOGLE_SITE_VERIFICATION
    ? { google: process.env.GOOGLE_SITE_VERIFICATION }
    : undefined,
};

export const viewport = {
  themeColor: "#039855",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {ADSENSE_CLIENT && (
          <Script
            id="adsbygoogle-init"
            async
            strategy="afterInteractive"
            crossOrigin="anonymous"
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_CLIENT}`}
          />
        )}
        <JsonLd data={organizationLd()} />
        <JsonLd data={websiteLd()} />
        <AuthProvider>
          <Navbar />
          <main className="min-h-[calc(100vh-4rem)]">{children}</main>
          <footer className="mt-16 border-t border-gray-200 bg-white">
            <div className="container-page py-10 text-sm text-gray-500">
              <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
                <div>
                  <div className="flex items-center gap-2 text-base font-extrabold text-brand-700">
                    <span className="grid h-7 w-7 place-items-center rounded-lg bg-brand-600 text-white">N</span>
                    NaijaArtisans
                  </div>
                  <p className="mt-3 max-w-xs text-gray-500">
                    Find trusted artisans near you — plumbers, electricians, tailors, carpenters and
                    more, across all 36 states &amp; FCT. 🇳🇬
                  </p>
                </div>

                <div>
                  <p className="font-semibold text-gray-900">Explore</p>
                  <ul className="mt-3 space-y-2">
                    <li><Link href="/browse" className="hover:text-brand-700">Find Artisans</Link></li>
                    <li><Link href="/jobs" className="hover:text-brand-700">Job Board</Link></li>
                    <li><Link href="/guides" className="hover:text-brand-700">Guides</Link></li>
                    <li><Link href="/join" className="hover:text-brand-700">For Artisans</Link></li>
                    <li><Link href="/pricing" className="hover:text-brand-700">Pricing</Link></li>
                  </ul>
                </div>

                <div>
                  <p className="font-semibold text-gray-900">Company</p>
                  <ul className="mt-3 space-y-2">
                    <li><Link href="/about" className="hover:text-brand-700">About</Link></li>
                    <li><Link href="/contact" className="hover:text-brand-700">Contact</Link></li>
                    <li><Link href="/help" className="hover:text-brand-700">Help &amp; FAQ</Link></li>
                    <li><Link href="/terms" className="hover:text-brand-700">Terms of Service</Link></li>
                    <li><Link href="/privacy" className="hover:text-brand-700">Privacy Policy</Link></li>
                  </ul>
                </div>

                <div>
                  <p className="font-semibold text-gray-900">Connect</p>
                  <ul className="mt-3 space-y-2">
                    <li>
                      <a href="mailto:support@naijaartisans.com" className="font-medium text-brand-700 hover:underline">
                        support@naijaartisans.com
                      </a>
                    </li>
                  </ul>
                  <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-2">
                    <a href="https://facebook.com/naijaartisans" target="_blank" rel="noopener noreferrer" aria-label="Facebook" className="hover:text-brand-700">Facebook</a>
                    <a href="https://instagram.com/naijaartisans" target="_blank" rel="noopener noreferrer" aria-label="Instagram" className="hover:text-brand-700">Instagram</a>
                    <a href="https://linkedin.com/company/naijaartisans" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" className="hover:text-brand-700">LinkedIn</a>
                    <a href="https://tiktok.com/@naijaartisans" target="_blank" rel="noopener noreferrer" aria-label="TikTok" className="hover:text-brand-700">TikTok</a>
                    <a href="https://youtube.com/@naijaartisans" target="_blank" rel="noopener noreferrer" aria-label="YouTube" className="hover:text-brand-700">YouTube</a>
                  </div>
                </div>
              </div>

              <div className="mt-8 border-t border-gray-100 pt-5 text-center text-xs text-gray-400">
                © {new Date().getFullYear()} NaijaArtisans. All rights reserved. Made for Nigeria 🇳🇬
                <span className="mx-1.5">·</span>
                Built by{" "}
                <a
                  href="https://samuel-ijeluola.netlify.app"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-medium text-brand-600 hover:underline"
                >
                  Samuel Ijeluola
                </a>
              </div>
            </div>
          </footer>
        </AuthProvider>
        <ChatWidget />
        <ServiceWorkerRegister />
        <Analytics />
      </body>
    </html>
  );
}
